### ISSUE TITLE
ButtonActivatedPlatform ignore properties

### ISSUE THREAD

**Issue by MarioChao** [jukes-towers-of-hell/kit#1]
In the `activatePlatform()` function of [CacheHandler init](https://github.com/jukes-towers-of-hell/kit/blob/main/src/Client/Repository/Button/CacheHandler/init.luau), there's this loop that modifies the `Transparency` (`BackgroundTransparency`, `GroupTransparency`, `TextTransparency`, `ImageTransparency`) and `Enabled` properties of several instances.

```lua
for _, descendant: Instance in platform:GetDescendants() do --rip "asfd", you may or may not be missed
	if descendant.Name == "Activated" and descendant:IsA("BoolValue") then descendant.Value = isActivated end
	if utility.hasTag(descendant, "IgnoreAll") then continue end
	for objectType, property in TWEEN_TRANSPARENCY_PROPERTIES do
		if descendant:IsA(objectType) then
			utility.tween(descendant, 0.3, { [property] = getTransparency(descendant, isActivated) })
		end
	end

	for _, objectType: string in SET_PROPERTIES_ENABLED do
		if descendant:IsA(objectType) then (descendant :: any).Enabled = isActivated end
	end
end
```

In addition to `IgnoreAll`, shouldn't there be a `IgnoreTransparency` check before modifying `Transparency`?
Also, probably unnecessary, but there can also be a `IgnoreEnabled` check for changing the `Enabled` property.

**Comment by synnwave** [comment]
oops, yes
there's a lot of things that i overlooked while rewriting that button script, mainly because i was just excited to get the first script done lol
